spring.application.name=api-gateway
server.port=9191
#actuator
management.endpoints.web.exposure.include=*

#configuring eureka service registry and discovery client
eureka.client.service-url.defaultzone=http://localhost:8761/eureka/

#Routes for employees Service
spring.cloud.gateway.routes[0].id=employee-service
spring.cloud.gateway.routes[0].uri=lb://employee-service

#Enable all api having api/employees using **
spring.cloud.gateway.routes[0].predicates[0]=Path=/employee/**


#Routes for Department Service
spring.cloud.gateway.routes[1].id=department-service
spring.cloud.gateway.routes[1].uri=lb://department-service

#Enable all api having api/departments using **
#spring.cloud.gateway.routes[1].predicates[0]=Path=/department,/department/**

spring.cloud.gateway.routes[1].predicates[0]=Path=/department
#spring.cloud.gateway.routes[1].predicates[0]=Path=/department/**
spring.cloud.gateway.routes[1].predicates[1]=Path=/department/**

