spring.application.name=department-service
server.port=8092
spring.datasource.url=jdbc:postgresql://localhost:5432/departmentService_MyWorkingMS
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
