spring.application.name=department-service

#import properties has opional:configserver:uri of config server
spring.config.import=optional:configserver:http://localhost:8888
management.endpoints.web.exposure.include=*

##commenting coz have stored in github in config repository 

#server.port=8093
#spring.datasource.url=jdbc:postgresql://localhost:5432/departmentService_MyWorkingMS
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.driver-class-name=org.postgresql.Driver

##Eureka service registry and discovery
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

