spring.application.name=employee-service

##Commenting as these are stored in the config repository
#server.port=8091
#spring.datasource.url=jdbc:postgresql://localhost:5432/employee_Service_MyWorkingMS
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.jpa.hibernate.ddl-auto=create
#spring.datasource.driver-class-name=org.postgresql.Driver

#import properties
spring.config.import=optional:configserver:http://localhost:8888

#for docker rabbitmq config

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
